# fly.toml app configuration file generated for fundflow-demo on 2025-07-27T10:40:59+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fundflow-demo'
primary_region = 'sea'

[build]
  image = 'fundfl0w/fundflow:latest'

[env]
  ALLOWED_HOSTS = 'fundflow-demo.fly.dev,app.fundflow.dev,172.19.18.170,localhost'
  DJANGO_DEBUG = 'False'
  DJANGO_SETTINGS_MODULE = 'FundFlow.settings'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
