# Generated by Django 5.1.7 on 2025-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_category_transaction_category_string_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('plaid_item', 'account_id')},
        ),
    ]
