# Generated by Django 5.1.7 on 2025-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_currency',
            field=models.CharField(default='AUD', help_text="The user's preferred base currency for reporting (e.g., AUD, USD, EUR).", max_length=3),
        ),
    ]
