# Generated by Django 5.1.7 on 2025-04-19 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the category (e.g., 'Groceries', 'Rent', 'Alcohol').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for creating hierarchy. Null for top-level categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='transactions.category')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this category. Null for system categories.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('user', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('description', models.TextField(help_text='Description of the transaction (e.g., merchant name, notes).')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the transaction.', max_digits=12)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='Whether the amount is a Debit (outgoing) or Credit (incoming).', max_length=10)),
                ('source_account_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('counterparty_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('source_code', models.CharField(blank=True, max_length=10, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_notifications', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
