# Generated by Django 5.1.7 on 2025-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique transaction ID provided by the bank API (if applicable).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV Upload'), ('up_bank', 'Up Bank API')], db_index=True, default='csv', help_text='Source from which this transaction was created.', max_length=20),
        ),
    ]
