# Generated by Django 5.1.7 on 2025-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_bank_transaction_id_transaction_source'),
    ]

    operations = [
        # This is what Django likely generated:
        # migrations.RemoveField(
        #     model_name='transaction',
        #     name='amount',
        # ),
        # migrations.AddField(
        #     model_name='transaction',
        #     name='original_amount',
        #     field=models.DecimalField(decimal_places=2, default=0, help_text='The amount of the transaction in the original currency.', max_digits=12),
        #     preserve_default=False,
        # ),
        #
        # !!! REPLACE THE TWO OPERATIONS ABOVE WITH THIS RenameField OPERATION: !!!
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='original_amount',
        ),
        #
        # Then the other AddField operations:
        migrations.AddField(
            model_name='transaction',
            name='aud_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The equivalent amount of the transaction in AUD, converted using the rate on the transaction date.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_to_aud',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Exchange rate used to convert original_amount to aud_amount (Original Currency to AUD).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            # Use the default string 'XXX' we discussed
            field=models.CharField(db_index=True, default='XXX', help_text='ISO 4217 currency code of the original transaction (e.g., AUD, EUR).', max_length=3),
            preserve_default=False, # Django adds this when you provide a one-off default
        ),
    ]
