# Generated by Django 5.1.7 on 2025-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_original_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('csv', 'CSV Upload'), ('up_bank', 'Up Bank API'), ('manual', 'Manual Entry')], db_index=True, default='csv', help_text='Source from which this transaction was created.', max_length=20),
        ),
    ]
