# Generated by Django 5.1.7 on 2025-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_vendor_transaction_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_aud_conversion_manual',
            field=models.BooleanField(default=False, help_text='Whether the AUD conversion was manually set by a user or automatically calculated.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manual_conversion_note',
            field=models.TextField(blank=True, help_text='Optional note explaining the manual conversion reasoning.', null=True),
        ),
    ]
