# Generated by Django 5.1.7 on 2025-06-06 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_add_conversion_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('calculated_balance', models.DecimalField(decimal_places=2, help_text='Balance calculated by our system', max_digits=12)),
                ('authoritative_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Balance from authoritative source (e.g., Up Bank API)', max_digits=12, null=True)),
                ('discrepancy', models.DecimalField(decimal_places=2, help_text='Absolute difference between calculated and authoritative balance', max_digits=12)),
                ('discrepancy_percent', models.DecimalField(decimal_places=4, help_text='Discrepancy as a percentage of authoritative balance', max_digits=8)),
                ('validation_source', models.CharField(help_text="Source of authoritative balance (e.g., 'up_bank', 'ing', 'manual')", max_length=50)),
                ('target_currency', models.CharField(default='AUD', help_text='Currency used for balance comparison', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the validation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='transaction_user_id_b78890_idx'), models.Index(fields=['validation_source', '-timestamp'], name='transaction_validat_98221a_idx')],
            },
        ),
    ]
