# Generated by Django 5.1.7 on 2025-06-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_add_balance_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_base_currency',
            field=models.CharField(db_index=True, default='AUD', help_text='Currency of the source account (e.g., AUD for Up Bank, EUR for ING Bank CSV uploads).', max_length=3),
        ),
        migrations.DeleteModel(
            name='BalanceValidation',
        ),
    ]
