# Generated by Django 5.1.7 on 2025-06-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_add_account_base_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMerge',
            fields=[
                ('id', models.CharField(help_text='UUID for the vendor merge operation.', max_length=36, primary_key=True, serialize=False)),
                ('merged_vendor_ids', models.JSONField(help_text='Array of vendor IDs that have been merged into the primary vendor.')),
                ('merged_descriptions', models.JSONField(help_text='Array of original vendor descriptions/names that were merged.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_vendor', models.ForeignKey(help_text='The vendor that remains active after merging.', on_delete=django.db.models.deletion.CASCADE, related_name='primary_merges', to='transactions.vendor')),
                ('updated_by', models.ForeignKey(help_text='User who performed the merge operation.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Merge',
                'verbose_name_plural': 'Vendor Merges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['primary_vendor'], name='transaction_primary_f3852d_idx'), models.Index(fields=['created_at'], name='transaction_created_383d5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorRule',
            fields=[
                ('id', models.CharField(help_text='UUID for the vendor rule.', max_length=36, primary_key=True, serialize=False)),
                ('pattern', models.CharField(blank=True, help_text='Optional regex pattern for description matching. If null, rule applies to all transactions from this vendor.', max_length=500, null=True)),
                ('is_persistent', models.BooleanField(db_index=True, default=False, help_text='If true, automatically assign this category to future transactions from this vendor.')),
                ('priority', models.IntegerField(choices=[(1, 'Very High'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Very Low')], db_index=True, default=3, help_text='Priority level for rule conflict resolution (1=highest, 5=lowest).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category to assign when this rule matches.', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_rules', to='transactions.category')),
                ('vendor', models.ForeignKey(help_text='The vendor this rule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='categorization_rules', to='transactions.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Rule',
                'verbose_name_plural': 'Vendor Rules',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['vendor', 'priority'], name='transaction_vendor__4551de_idx'), models.Index(fields=['category'], name='transaction_categor_71509d_idx'), models.Index(fields=['is_persistent'], name='transaction_is_pers_84af80_idx')],
            },
        ),
    ]
