# Generated by Django 5.1.7 on 2025-06-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_create_vendor_merge_and_vendor_rule_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_parent_split',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this transaction has been split into multiple categories.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, help_text='If this is a child transaction from a split, reference to the parent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_transactions', to='transactions.transaction'),
        ),
        migrations.CreateModel(
            name='SplitTransaction',
            fields=[
                ('id', models.CharField(help_text='UUID for the split transaction.', max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount allocated to this split (must be positive).', max_digits=12)),
                ('description', models.CharField(help_text="Custom description for this split portion (e.g., 'Groceries portion of Walmart purchase').", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='The category assigned to this split portion.', on_delete=django.db.models.deletion.CASCADE, related_name='split_transactions', to='transactions.category')),
                ('parent_transaction', models.ForeignKey(help_text='The original transaction that this split belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='split_transactions', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Split Transaction',
                'verbose_name_plural': 'Split Transactions',
                'ordering': ['parent_transaction', 'created_at'],
                'indexes': [models.Index(fields=['parent_transaction'], name='transaction_parent__5eb976_idx'), models.Index(fields=['category'], name='transaction_categor_097c13_idx'), models.Index(fields=['created_at'], name='transaction_created_64b950_idx')],
            },
        ),
    ]
