# Generated by Django 5.1.7 on 2025-06-10 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_add_split_transaction_model_and_parent_child_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomView',
            fields=[
                ('id', models.CharField(help_text='UUID for the custom view.', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the custom view (e.g., 'Q4 Business Expenses', 'Vacation Planning').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this view is used for.', null=True)),
                ('search_criteria', models.JSONField(help_text='JSON object containing search parameters like date ranges, vendors, amounts, etc.')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether this view has been archived (hidden from active use).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this custom view.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom View',
                'verbose_name_plural': 'Custom Views',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.CharField(help_text='UUID for the custom category.', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the custom category (e.g., 'Travel Food', 'Project Expenses').", max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order within the parent category or view.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent custom category for creating hierarchy. Null for top-level categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='transactions.customcategory')),
                ('custom_view', models.ForeignKey(help_text='The custom view this category belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='transactions.customview')),
            ],
            options={
                'verbose_name': 'Custom Category',
                'verbose_name_plural': 'Custom Categories',
                'ordering': ['custom_view', 'parent', 'order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='customview',
            index=models.Index(fields=['user', 'is_archived'], name='transaction_user_id_5193e1_idx'),
        ),
        migrations.AddIndex(
            model_name='customview',
            index=models.Index(fields=['created_at'], name='transaction_created_9410c6_idx'),
        ),
        migrations.AddIndex(
            model_name='customview',
            index=models.Index(fields=['updated_at'], name='transaction_updated_99a2df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customview',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='customcategory',
            index=models.Index(fields=['custom_view', 'parent'], name='transaction_custom__8803b0_idx'),
        ),
        migrations.AddIndex(
            model_name='customcategory',
            index=models.Index(fields=['custom_view', 'order'], name='transaction_custom__642b94_idx'),
        ),
        migrations.AddIndex(
            model_name='customcategory',
            index=models.Index(fields=['parent'], name='transaction_parent__0bf649_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customcategory',
            unique_together={('custom_view', 'parent', 'name')},
        ),
    ]
