# Generated by Django 5.1.7 on 2025-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_create_custom_view_and_custom_category_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcategory',
            options={'ordering': ['custom_view', 'order', 'name'], 'verbose_name': 'Custom Category', 'verbose_name_plural': 'Custom Categories'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['display_name', 'name']},
        ),
        migrations.AddField(
            model_name='vendor',
            name='description_patterns',
            field=models.JSONField(default=list, help_text='Array of description patterns that help identify this vendor in transaction descriptions.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='display_name',
            field=models.CharField(default='', help_text="Display name for the vendor, used in UI (e.g., 'Woolworths Supermarket', 'Shell Gas Station').", max_length=255),
        ),
    ]
