# Generated by Django 5.1.7 on 2025-06-10 11:33

from django.db import migrations


def populate_vendor_display_names(apps, schema_editor):
    """
    Populate display_name field with the value from name field for all existing vendors.
    """
    Vendor = apps.get_model('transactions', 'Vendor')
    
    vendors_to_update = []
    for vendor in Vendor.objects.filter(display_name=''):
        vendor.display_name = vendor.name
        vendors_to_update.append(vendor)
    
    if vendors_to_update:
        Vendor.objects.bulk_update(vendors_to_update, ['display_name'])
        print(f"Updated display_name for {len(vendors_to_update)} vendors")


def reverse_populate_vendor_display_names(apps, schema_editor):
    """
    Reverse operation: clear display_name field for all vendors.
    """
    Vendor = apps.get_model('transactions', 'Vendor')
    Vendor.objects.update(display_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_update_vendor_model_add_display_name_and_description_patterns'),
    ]

    operations = [
        migrations.RunPython(
            populate_vendor_display_names,
            reverse_populate_vendor_display_names,
        ),
    ]
