# Generated by Django 5.1.7 on 2025-06-10 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_populate_vendor_display_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'parent'], name='transaction_user_id_583d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='transaction_parent__16746b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='transaction_created_9abe5e_idx'),
        ),
        migrations.AddIndex(
            model_name='descriptionmapping',
            index=models.Index(fields=['user'], name='transaction_user_id_7f74e7_idx'),
        ),
        migrations.AddIndex(
            model_name='descriptionmapping',
            index=models.Index(fields=['assigned_category'], name='transaction_assigne_7c71b0_idx'),
        ),
        migrations.AddIndex(
            model_name='descriptionmapping',
            index=models.Index(fields=['created_at'], name='transaction_created_bc53a6_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalexchangerate',
            index=models.Index(fields=['date', 'source_currency'], name='transaction_date_9ef50c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalexchangerate',
            index=models.Index(fields=['source_currency', 'target_currency'], name='transaction_source__8db5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalexchangerate',
            index=models.Index(fields=['date'], name='transaction_date_25a815_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='transaction_user_id_e55ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='transaction_user_id_cb8cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'vendor'], name='transaction_user_id_457834_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date', 'original_currency'], name='transaction_transac_a3d308_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source', 'user'], name='transaction_source_4a22aa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_parent_split'], name='transaction_is_pare_e9b3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['parent_transaction'], name='transaction_parent__ba8440_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bank_transaction_id'], name='transaction_bank_tr_d963c4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['original_currency', 'transaction_date'], name='transaction_origina_fff940_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='transaction_user_id_f5864b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['user'], name='transaction_user_id_d3c76a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['display_name'], name='transaction_display_050968_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['created_at'], name='transaction_created_f9d0c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalexchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='positive_exchange_rate'),
        ),
        migrations.AddConstraint(
            model_name='splittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_split_amount'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='positive_original_amount'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('aud_amount__isnull', True), ('aud_amount__gt', 0), _connector='OR'), name='positive_aud_amount_when_present'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate_to_aud__isnull', True), ('exchange_rate_to_aud__gt', 0), _connector='OR'), name='positive_exchange_rate_when_present'),
        ),
        migrations.AddConstraint(
            model_name='vendorrule',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 5)), name='valid_priority_range'),
        ),
    ]
