# Generated by Django 5.1.7 on 2025-06-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_add_performance_indexes_and_validation_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTransaction',
            fields=[
                ('id', models.CharField(help_text='UUID for the view transaction assignment.', max_length=36, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='Optional notes specific to this transaction within this view context.', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this transaction was assigned to the custom view.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this assignment was last updated.')),
                ('custom_category', models.ForeignKey(blank=True, help_text='The custom category assigned to this transaction within the view. Null if uncategorized in this view.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_transactions', to='transactions.customcategory')),
                ('custom_view', models.ForeignKey(help_text='The custom view this transaction assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='view_transactions', to='transactions.customview')),
                ('transaction', models.ForeignKey(help_text='The transaction assigned to this custom view.', on_delete=django.db.models.deletion.CASCADE, related_name='view_assignments', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'View Transaction',
                'verbose_name_plural': 'View Transactions',
                'ordering': ['custom_view', '-assigned_at'],
                'indexes': [models.Index(fields=['custom_view', 'custom_category'], name='transaction_custom__c96285_idx'), models.Index(fields=['transaction', 'custom_view'], name='transaction_transac_a7cafa_idx'), models.Index(fields=['custom_category'], name='transaction_custom__0d7a9d_idx'), models.Index(fields=['assigned_at'], name='transaction_assigne_6f758d_idx')],
                'unique_together': {('custom_view', 'transaction')},
            },
        ),
    ]
