# Generated by Django 5.1.7 on 2025-06-13 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_add_view_transaction_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'transaction_date'], name='transaction_user_id_6664bc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'vendor', 'transaction_date'], name='transaction_user_id_d72aba_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'original_amount', 'transaction_date'], name='transaction_user_id_44cba6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'direction', 'transaction_date'], name='transaction_user_id_482213_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'source', 'transaction_date'], name='transaction_user_id_3abaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['description'], name='tx_desc_text_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(condition=models.Q(('category__isnull', True)), fields=['user', 'category'], name='tx_uncategorized_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_parent_split', 'transaction_date'], name='transaction_user_id_7de17b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'aud_amount', 'transaction_date'], name='transaction_user_id_958d42_idx'),
        ),
    ]
