# Generated by Django 5.1.7 on 2025-06-22 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20250616_0738'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='The original vendor name as it appears in transaction data.', max_length=255)),
                ('mapped_vendor', models.CharField(help_text='The standardized vendor name this original name maps to.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Mapping',
                'verbose_name_plural': 'Vendor Mappings',
                'ordering': ['mapped_vendor', 'original_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='vendorrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vendor Rule', 'verbose_name_plural': 'Vendor Rules'},
        ),
        # Constraint and index already removed in previous migration
        migrations.AddField(
            model_name='vendormapping',
            name='user',
            field=models.ForeignKey(help_text='User who owns this vendor mapping.', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vendormapping',
            index=models.Index(fields=['user', 'original_name'], name='transaction_user_id_467783_idx'),
        ),
        migrations.AddIndex(
            model_name='vendormapping',
            index=models.Index(fields=['mapped_vendor'], name='transaction_mapped__32c2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendormapping',
            index=models.Index(fields=['created_at'], name='transaction_created_98eae3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendormapping',
            unique_together={('user', 'original_name')},
        ),
    ]
