# Generated by Django 5.1.7 on 2025-07-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20250622_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this transaction has been hidden from the review page.'),
        ),
    ]
