# Generated by Django 5.1.7 on 2025-07-20 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_add_is_hidden_field_simple'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text="User's decision on the auto-categorization.", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Import Review Decision',
                'verbose_name_plural': 'Import Review Decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.CharField(help_text='UUID for the import session.', max_length=36, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('csv', 'CSV Upload'), ('up_bank', 'Up Bank API'), ('manual', 'Manual Entry')], help_text='Source of the import (CSV, API, etc.).', max_length=20)),
                ('total_transactions', models.IntegerField(default=0, help_text='Total number of transactions in the import.')),
                ('new_transactions', models.IntegerField(default=0, help_text='Number of new (non-duplicate) transactions.')),
                ('auto_categorized', models.IntegerField(default=0, help_text='Number of transactions that were auto-categorized.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Import Session',
                'verbose_name_plural': 'Import Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='vendorrule',
            name='valid_priority_range',
        ),
        migrations.RemoveIndex(
            model_name='vendorrule',
            name='transaction_vendor__4551de_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_32729f_idx',
            old_name='transactions_user_vendor_name_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_f48353_idx',
            old_name='transactions_user_original_vendor_name_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_auto_ca_6b6210_idx',
            old_name='transactions_auto_categorized_idx',
        ),
        migrations.AddField(
            model_name='importreviewdecision',
            name='transaction',
            field=models.ForeignKey(help_text='The transaction being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='import_review_decisions', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='user',
            field=models.ForeignKey(help_text='User who performed the import.', on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importreviewdecision',
            name='import_session',
            field=models.ForeignKey(help_text='The import session this decision belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='transactions.importsession'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['user', 'created_at'], name='transaction_user_id_0f35ca_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['source'], name='transaction_source_eee910_idx'),
        ),
        migrations.AddIndex(
            model_name='importreviewdecision',
            index=models.Index(fields=['import_session', 'decision'], name='transaction_import__fe38d0_idx'),
        ),
        migrations.AddIndex(
            model_name='importreviewdecision',
            index=models.Index(fields=['transaction'], name='transaction_transac_c2a330_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importreviewdecision',
            unique_together={('import_session', 'transaction')},
        ),
    ]
