# Generated by Django 5.1.7 on 2025-07-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_add_import_review_models_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Parent category for this vendor in the tree structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='transactions.category'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['parent_category'], name='transaction_parent__5be0d4_idx'),
        ),
    ] 