# Generated by Django 5.1.7 on 2025-07-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_make_vendor_user_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importreviewdecision',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='importreviewdecision',
            name='import_session',
        ),
        migrations.RemoveField(
            model_name='importreviewdecision',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='importsession',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='vendorrule',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'Vendor Rule', 'verbose_name_plural': 'Vendor Rules'},
        ),
        migrations.RemoveField(
            model_name='vendorrule',
            name='pattern',
        ),
        migrations.AddIndex(
            model_name='vendorrule',
            index=models.Index(fields=['vendor', 'priority'], name='transaction_vendor__4551de_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorrule',
            constraint=models.UniqueConstraint(fields=('vendor',), name='unique_vendor_rule'),
        ),
        migrations.DeleteModel(
            name='ImportReviewDecision',
        ),
        migrations.DeleteModel(
            name='ImportSession',
        ),
    ]
